#!/bin/sh
set -e

# clean up ENV vars left over from build
unset GPG_KEYS \
    PHP_ASC_URL \
    PHP_CFLAGS \
    PHP_CPPFLAGS \
    PHP_EXTRA_CONFIGURE_ARGS \
    PHP_INI_DIR PHP_LDFLAGS \
    PHP_SHA256 \
    PHP_URL \
    PHP_VERSION \
    PHPIZE_DEPS

/usr/local/bin/wait > /dev/null

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php "$@"
fi

exec "$@"
